export const viewingPageWrapper: string
export const viewingPageImageWrapper: string
export const viewingPageImageContentWrapper: string
export const viewingPageName: string
export const viewingPageImageContentDivider: string
export const viewingPageContentTabWrapper: string
export const viewingPageContentContainer: string
export const viewingPageContentWrapper: string
export const viewingPageContentTitle: string
export const viewingPageContentDescription: string
export const viewingPageContentList: string
export const viewingPageContentListItem: string
export const viewingPageSideContentWrapper: string
export const viewingPageSideContentTopic: string
export const viewingPageSideContentInfo: string
export const viewingPageNoInfo: string
