export const bloodDonorPageWrapper: string
export const bloodDonorPageTitle: string
export const bloodDonorFilterWrapper: string
export const bloodDonorFilterTab: string
export const bloodDonorFilterTabActive: string
export const bloodDonorFilterButton: string
export const bloodDonorListWrapper: string
export const bloodDonorListStartCard: string
export const bloodDonorListCard: string
