export const headerContainer: string
export const headerContentWrapper: string
export const headerSubContentWrapper: string
export const headerLeftSide: string
export const headerActionButton: string
export const headerActionRedButton: string
export const headerRightSide: string
export const headerRightNotificationIcon: string
export const headerRightProfileImage: string
export const headerSubContentForm: string
export const headerSubContentFormLabel: string
export const headerSubContentWrapperRedBg: string
export const headerSubContentFormRadio: string
export const headerSubContentFormRadioActive: string
export const headerSubContentTitle: string
export const headerSubContentFormField: string
