export const eventCarouselWrapper: string
export const eventCarouselContentWrapper: string
export const eventCardWrapper: string
export const eventCardImage: stting
export const notLastCard: string
export const eventCardContentWrapper: string
export const eventCardTitle: string
export const eventCardTag: string
export const eventCardInfoWrapper: string
export const eventCardButtonWrapper: string
export const eventCardDate: string
export const eventCardTagDateWrapper: string
export const eventCardBlur: string
