export const hostCarouselWrapper: string
export const hostCarouselContentWrapper: string
export const hostCardWrapper: string
export const notLastHostCard: string
export const hostCardContentWrapper: string
export const hostCardTitle: string
export const hostCardCompany: string
export const hostCardDescription: string
export const hostCardBlur: string
