export const requestWrapper: string
export const requestCardContainer: string
export const requestCardWrapper: string
export const requestCardInfoWrapper: string
export const requestCardImage: string
export const requestCardBloodGroup: string
export const requestCardName: string
export const requestCardContactInfo: string
export const requestCardStatusOrActionWrapper: string
export const requestActionSelected: string
export const requestCardForm: string
export const requestCardFormTextArea: string
export const requestCardStatus: string
export const requestPending: string
export const requestAccepted: string
export const requestDeclined: string
export const requestCardMessage: string
