export const hospitalCarouselWrapper: string
export const hospitalCarouselContentWrapper: string
export const hospitalCardWrapper: string
export const hospitalCardImage: string
export const notLastCard: string
export const hospitalCardContentWrapper: string
export const hospitalCardTitle: string
export const hospitalCardTag: string
export const hospitalCardInfoWrapper: string
export const hospitalCardButtonWrapper: string
export const hospitalCardTagDateWrapper: string
export const hospitalCardBlur: string
