export const educationWrapper: string
export const educationButton: string
export const educationForm: string
export const educationContentWrapper: string
export const educationInstituteName: string
export const educationDegree: string
export const educationInstituteAddress: string
export const educationYear: string
export const educationContentEdit: string
