export const ambulanceCarouselWrapper: string
export const ambulanceCarouselContentWrapper: string
export const ambulanceCardWrapper: string
export const notLastCard: string
export const ambulanceCardContentWrapper: string
export const ambulanceCardTitle: string
export const ambulanceCardImage: string
export const ambulanceCardTag: string
export const ambulanceCardInfoWrapper: string
export const ambulanceCardButtonWrapper: string
export const ambulanceCardDate: string
export const ambulanceCardTagDateWrapper: string
export const ambulanceCardBlur: string
