export const bloodBankCarouselWrapper: string
export const bloodBankCarouselContentWrapper: string
export const bloodBankCardWrapper: string
export const notLastCard: string
export const bloodBankCardContentWrapper: string
export const bloodBankCardTitle: string
export const bloodBankCardTag: string
export const bloodBankCardInfoWrapper: string
export const bloodBankCardButtonWrapper: string
export const bloodBankCardDate: string
export const bloodBankCardTagDateWrapper: string
export const bloodBankCardBlur: string
export const bloodBankCardImage: string
